version: '3.3'
services:

  demo:
    container_name: demo
    build: .
    ports:
      - "8080:8080"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
      - elasticsearch
    networks:
      - backend

  db:
    image: postgres:12
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=demo
      - PGDATA=/var/lib/postgresql/data/pgdata

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch_development_container
    volumes:
      - /var/db/data/elasticsearch:/Users/docker_volumes/elasticsearch_bkp
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  esdata1:
    driver: local

networks:
  backend:
    name: demo
    driver: bridge
