spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/demo
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    rest:
      connection-timeout: 30
      uris:
      - elasticsearch:9200
